apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "dgraph"
  labels:
    app.kubernetes.io/name: "dgraph"
    app.kubernetes.io/version: "0.1.0"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "dgraph"
  componentKinds:
    - group: core
      kind: Service
    - group: core
      kind: Ingress
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
  descriptor:
    links:
      - description: Open Dgraph Enterprise
        url: "http://ratel-http"
