apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dgraph-ingress
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_ingress" "1" }}'
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: dgraph-public
            servicePort: 8000

