---
# This is the service that should be used by the clients of Dgraph to talk to the cluster.
apiVersion: v1
kind: Service
metadata:
  name: dgraph-public
  labels:
    app: dgraph
spec:
  type: NodePort
  ports:
  - port: 5080
    targetPort: 5080
    name: zero-grpc
  - port: 6080
    targetPort: 6080
    nodePort: 36080
    name: zero-http
  - port: 8080
    targetPort: 8080
    nodePort: 38080
    name: alpha-http
  - port: 9080
    targetPort: 9080
    name: alpha-grpc
  - port: 8000
    targetPort: 8000
    nodePort: 38000
    name: ratel-http
  selector:
    app: dgraph
