apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: dgraph-enterprise
spec:
  title: Dgraph Enterprise
  icon: https://img.stackshare.io/service/7071/MrEYkPFd_400x400.jpg
  statusInformers:
    - statefulset/dgraph
    - service/dgraph-public
